### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by FRidh** [nikstur/bombon#42] opened 2023-04-16 08:30 UTC
Failing build at 9bf3e29ca898d4d646dc9998e8060c5a4de1442c. Not using any `follows` but if I do so (for nixpkgs-unstable) the issue persists. Works ok against `nixos-22.11`.

```sh
$ nix build .#sbom-nash-api
warning: Git tree '/home/freddy/code/nash/backend' is dirty
error: builder for '/nix/store/kghq8y61l8bhbhqi753w9rfrnyfyjc38-rustfmt-preview-1.64.0-x86_64-unknown-linux-gnu.drv' failed with exit code 1;
       last 10 log lines:
       > searching for dependencies of /nix/store/jxl86ppjyh79bq7l3max3gh3243h7ikr-rustfmt-preview-1.64.0-x86_64-unknown-linux-gnu/bin/cargo-fmt
       >     libgcc_s.so.1 -> not found!
       > auto-patchelf: 2 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/jxl86ppjyh79bq7l3max3gh3243h7ikr-rustfmt-preview-1.64.0-x86_64-unknown-linux-gnu/bin/rustfmt
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/jxl86ppjyh79bq7l3max3gh3243h7ikr-rustfmt-preview-1.64.0-x86_64-unknown-linux-gnu/bin/cargo-fmt
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/kghq8y61l8bhbhqi753w9rfrnyfyjc38-rustfmt-preview-1.64.0-x86_64-unknown-linux-gnu.drv'.
error: 1 dependencies of derivation '/nix/store/g004xzj1jynbrp1h5q2i2277df47k9fn-rust-default-1.64.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1y0dbbv984rfwi5hsr8i2k5hl0ycp9pl-bombon-transformer-0.1.0.drv' failed to build
```

**Comment by FRidh** [comment] 2023-04-19 09:20
I used it against the `nixos-22.11` branch and then it did work.

Seems something is not reproducible here. Is this using IFD somewhere? Or somewhere a single hash covering many artifacts such as `cargoSha256`?

**Comment by nikstur** [comment] 2023-04-19 09:35
Thank you for the report. I'll look into it.

**Comment by nikstur** [comment] 2023-11-25 01:17
Since I couldn't reproduce this and everything is now completely updated I'm closing this. If this error occurs again, please re-open.

**Closed by nikstur** 2023-11-25 01:17 UTC
